=== BrayanBlu2/Reto2/reto2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
<xs:element name ="registro">
    <xs:complexType>
        <xs:sequence>
            <xs:element name ="reserva" maxOccurs="unbounded"> <!-- Abrimos el elemento reserva que contiene dos elementos dentro, fecha y cliente-->
             <xs:complexType>
                 <xs:sequence><!-- Es una secuencia porque deben aparecer los elementos una vez en el orden específico-->
                   <xs:element name = "fechaentrada" type ="xs:date" maxOccurs="unbounded"/><!-- Abrimos y cerramos el elemento fecha de entrada--> 
                   <xs:element name = "fechasalida" type ="xs:date" maxOccurs="unbounded"/><!-- Abrimos y cerramos el elemento fecha de salida-->                       
                    <xs:element name = "cliente" maxOccurs="unbounded">   <!-- Abrimos el elemento cliente que contiene más elementos dentro-->  
                        <xs:complexType>
                         <xs:sequence>
                             <xs:element name="nombre"> <!--Abrimos el elemento nombre-->
                             <xs:simpleType >
                                 <xs:restriction base ="xs:string"> <!-- Se trata de un elemento string -->
                                     <xs:pattern value = "[A-Z][a-z]*"/>
                                     <xs:maxLength value = "20"/><!-- Longitud máxima de 20 letras -->                 
                                 </xs:restriction>
                             </xs:simpleType>
                    </xs:element>
                        <xs:element name="apellido"> <!-- El elemento apellido que puede contener hasta 30 letras-->
                        <xs:simpleType>
                            <xs:restriction base ="xs:string"> 
                                <xs:pattern value = "[A-Z][a-z]*"/>
                                <xs:maxLength value = "30"/>                      
                            </xs:restriction>
                        </xs:simpleType> 
                    </xs:element>
                        <xs:element name= "teléfono"><!-- El elemento teléfono debe contener 9 dígitos-->
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:totalDigits value ="9"/>                                    
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name ="dirección"> <!-- Dirección contiene varios elementos dentro-->
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name ="calle" type ="xs:string"/>                                     
                                     <xs:element name="número">                
                                         <xs:simpleType>
                                            <xs:restriction base ="xs:integer"><!--Debe ir del número 0 al 700-->
                                                <xs:minExclusive value="0"/>
                                                <xs:maxExclusive value="700"/>
                                            </xs:restriction>                        
                                        </xs:simpleType>
                                     </xs:element>                
                                    <xs:element name="ciudad" type ="xs:string"/>                                    
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                 </xs:sequence>
                    <xs:attribute name="dni" type ="dniType"/><!-- Atributo de cliente, DNI-->
            </xs:complexType>
            </xs:element>
            <xs:element name ="cantidad"><!-- Elemento que se refiere al número de personas que contiene la reserva-->
            <xs:simpleType>
                <xs:restriction base ="xs:integer">
                    <xs:minInclusive value ="1"/>
                    <xs:maxInclusive value ="4"/><!-- Máximo 4 personas por cliente que hace una reserva-->                                
                </xs:restriction>
            </xs:simpleType>
           </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
                <xs:simpleType name="dniType"><!-- Definimos el atributo DNI fuera del resto de elementos-->
                    <xs:restriction base="xs:string">
                        <xs:pattern value ="[0-9]{8}[A-Z]"/>
                     </xs:restriction>
                </xs:simpleType>         

</xs:schema>

=== BrayanBlu2/Reto2/reto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reto2.xsd">
    <reserva>        
        <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
        <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="12345678A"> <!-- Datos del cliente que ha reservado para alojarse el 23/01/2023-->
            <nombre>Carlos</nombre> 
            <apellido>Alvarez</apellido>   
            <teléfono>654659825</teléfono> 
            <dirección>
                <calle>Los Astilleros</calle> 
                <número>12</número>
                <ciudad>Vigo</ciudad>
            </dirección>
    </cliente> 
    <cantidad>2</cantidad>  
</reserva>
<reserva> 
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="17896526B">
        <nombre>Marta</nombre> 
        <apellido>Rico</apellido>   
        <teléfono>666547898</teléfono> 
        <dirección>
            <calle>Lope de Vega</calle> 
            <número>34</número>
            <ciudad>Madrid</ciudad>
        </dirección> 
</cliente>
    <cantidad>1</cantidad> 
</reserva>
<reserva>
<fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
<fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
<cliente dni="72556897L">
    <nombre>Beatriz</nombre> 
    <apellido>Marcos</apellido>   
    <teléfono>647721321</teléfono> 
    <dirección>
        <calle>Borroto</calle> 
        <número>22</número>
        <ciudad>Donosti</ciudad>
    </dirección>
</cliente>
    <cantidad>2</cantidad>  
</reserva>
<reserva>
    <fechaentrada>2024-02-03</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-02-08</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="74589451F">
    <nombre>Gonzalo</nombre> 
    <apellido>Jaime</apellido>   
    <teléfono>666122136</teléfono> 
    <dirección>
        <calle>31 de agosto</calle> 
        <número>1</número>
        <ciudad>Vitoria</ciudad>
    </dirección>  
</cliente>
    <cantidad>2</cantidad>
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="12345678J">
    <nombre>Sonia</nombre> 
    <apellido>Arana</apellido>   
    <teléfono>622566939</teléfono> 
    <dirección>
        <calle>San Martin</calle> 
        <número>70</número>
        <ciudad>Valencia</ciudad>
    </dirección> 
</cliente>
    <cantidad>2</cantidad> 
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="72589654K">
    <nombre>Jorge</nombre> 
    <apellido>Ballesteros</apellido>   
    <teléfono>677894512</teléfono> 
    <dirección>
        <calle>Port del camp</calle> 
        <número>2</número>
        <ciudad>Lleida</ciudad>
    </dirección>
</cliente>
    <cantidad>1</cantidad>  
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="65978441M">
    <nombre>Alberto</nombre> 
    <apellido>Pla</apellido>   
    <teléfono>623315478</teléfono> 
    <dirección>
        <calle>Passeig de Gracia</calle> 
        <número>30</número>
        <ciudad>Barcelona</ciudad>
    </dirección> 
</cliente>
    <cantidad>1</cantidad> 
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="72589451D">
    <nombre>Alicia</nombre> 
    <apellido>Velez</apellido>   
    <teléfono>664489825</teléfono> 
    <dirección>
        <calle>Marina</calle> 
        <número>2</número>
        <ciudad>Barcelona</ciudad>
    </dirección> 
</cliente>
    <cantidad>2</cantidad> 
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="72256894L">
    <nombre>Montse</nombre> 
    <apellido>Fernandez</apellido>   
    <teléfono>654659825</teléfono> 
    <dirección>
        <calle>Avinguda Diagonal</calle> 
        <número>511</número>
        <ciudad>Barcelona</ciudad>
    </dirección>
</cliente>
    <cantidad>2</cantidad>  
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="44856899L">
    <nombre>Sara</nombre> 
    <apellido>Ramos</apellido>   
    <teléfono>654656785</teléfono> 
    <dirección>
        <calle>Port Olimpic</calle> 
        <número>23</número>
        <ciudad>Tarragona</ciudad>
    </dirección>  
</cliente>
    <cantidad>4</cantidad>
</reserva>
<reserva>    
        <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
        <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
        <cliente dni="12345678A">
            <nombre>Carlos</nombre> 
            <apellido>Alvarez</apellido>   
            <teléfono>654659825</teléfono> 
            <dirección>
                <calle>Los Astilleros</calle> 
                <número>12</número>
                <ciudad>Vigo</ciudad>
            </dirección>  
    </cliente> 
    <cantidad>2</cantidad>
</reserva>
<reserva>    
        <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
        <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
        <cliente dni="17896526B">
        <nombre>Marta</nombre> 
        <apellido>Rico</apellido>   
        <teléfono>666547898</teléfono> 
        <dirección>
            <calle>Lope de Vega</calle> 
            <número>34</número>
            <ciudad>Madrid</ciudad>
        </dirección> 
</cliente>
    <cantidad>1</cantidad> 
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="72556897L">
    <nombre>Beatriz</nombre> 
    <apellido>Marcos</apellido>   
    <teléfono>647721321</teléfono> 
    <dirección>
        <calle>Borroto</calle> 
        <número>22</número>
        <ciudad>Donosti</ciudad>
    </dirección>
</cliente>
    <cantidad>2</cantidad>  
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="72589451F">
    <nombre>Gonzalo</nombre> 
    <apellido>Jaime</apellido>   
    <teléfono>666122136</teléfono> 
    <dirección>
        <calle>31 de agosto</calle> 
        <número>1</número>
        <ciudad>Vitoria</ciudad>
    </dirección>  
</cliente>
    <cantidad>2</cantidad>  
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="12345678J">
    <nombre>Sonia</nombre> 
    <apellido>Arana</apellido>   
    <teléfono>622566939</teléfono> 
    <dirección>
        <calle>San Martin</calle> 
        <número>70</número>
        <ciudad>Valencia</ciudad>
    </dirección>  
</cliente>
    <cantidad>2</cantidad>
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="72589654K">
    <nombre>Jorge</nombre> 
    <apellido>Ballesteros</apellido>   
    <teléfono>677894512</teléfono> 
    <dirección>
        <calle>Port del camp</calle> 
        <número>2</número>
        <ciudad>Lleida</ciudad>
    </dirección> 
</cliente>
    <cantidad>1</cantidad> 
</reserva>
<reserva>
    <fechaentrada>2024-01-23</fechaentrada> <!-- La fecha de entrada de la primera reserva-->
    <fechasalida>2024-01-30</fechasalida><!-- La fecha de saluda de la primera reserva-->
    <cliente dni="65978441M">
    <nombre>Alberto</nombre> 
    <apellido>Pla</apellido>   
    <teléfono>623315478</teléfono> 
    <dirección>
        <calle>Passeig de Gracia</calle> 
        <número>30</número>
        <ciudad>Barcelona</ciudad>
    </dirección> 
</cliente>
    <cantidad>1</cantidad> 
</reserva>
</registro>
